interactions:
- request:
    body: '<?xml version=''1.0'' encoding=''utf-8''?>

      <StorageServiceProperties><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><AllowedHeaders
      /><ExposedHeaders /><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule><CorsRule><AllowedOrigins>www.xyz.com,www.ab.com,www.bc.com</AllowedOrigins><AllowedMethods>GET,PUT</AllowedMethods><AllowedHeaders>x-ms-meta-data*,x-ms-meta-target*,x-ms-meta-xyz,x-ms-meta-foo</AllowedHeaders><ExposedHeaders>x-ms-meta-data*,x-ms-meta-source*,x-ms-meta-abc,x-ms-meta-bcd</ExposedHeaders><MaxAgeInSeconds>500</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '631'
      Content-Type:
      - application/xml; charset=utf-8
      User-Agent:
      - azsdk-python-storage-blob/12.0.0b4 Python/3.7.3 (Windows-10-10.0.18362-SP0)
      x-ms-date:
      - Wed, 09 Oct 2019 21:50:43 GMT
      x-ms-version:
      - '2019-02-02'
    method: PUT
    uri: https://pyacrstorage84cb2225.blob.core.windows.net/?restype=service&comp=properties
  response:
    body:
      string: "\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server
        encountered an internal error. Please try again after some time.\nRequestId:9b769329-001c-00f1-44eb-7eea73000000\nTime:2019-10-09T21:50:45.2065728Z</Message></Error>"
    headers:
      content-length:
      - '254'
      content-type:
      - application/xml
      date:
      - Wed, 09 Oct 2019 21:50:44 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      x-ms-error-code:
      - InternalError
      x-ms-version:
      - '2019-02-02'
    status:
      code: 500
      message: Server encountered an internal error. Please try again after some time.
- request:
    body: '<?xml version=''1.0'' encoding=''utf-8''?>

      <StorageServiceProperties><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><AllowedHeaders
      /><ExposedHeaders /><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule><CorsRule><AllowedOrigins>www.xyz.com,www.ab.com,www.bc.com</AllowedOrigins><AllowedMethods>GET,PUT</AllowedMethods><AllowedHeaders>x-ms-meta-data*,x-ms-meta-target*,x-ms-meta-xyz,x-ms-meta-foo</AllowedHeaders><ExposedHeaders>x-ms-meta-data*,x-ms-meta-source*,x-ms-meta-abc,x-ms-meta-bcd</ExposedHeaders><MaxAgeInSeconds>500</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '631'
      Content-Type:
      - application/xml; charset=utf-8
      User-Agent:
      - azsdk-python-storage-blob/12.0.0b4 Python/3.7.3 (Windows-10-10.0.18362-SP0)
      x-ms-date:
      - Wed, 09 Oct 2019 21:50:43 GMT
      x-ms-version:
      - '2019-02-02'
    method: PUT
    uri: https://pyacrstorage84cb2225.blob.core.windows.net/?restype=service&comp=properties
  response:
    body:
      string: "\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server
        encountered an internal error. Please try again after some time.\nRequestId:9b76aacb-001c-00f1-66eb-7eea73000000\nTime:2019-10-09T21:51:02.3642233Z</Message></Error>"
    headers:
      content-length:
      - '254'
      content-type:
      - application/xml
      date:
      - Wed, 09 Oct 2019 21:51:01 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      x-ms-error-code:
      - InternalError
      x-ms-version:
      - '2019-02-02'
    status:
      code: 500
      message: Server encountered an internal error. Please try again after some time.
- request:
    body: '<?xml version=''1.0'' encoding=''utf-8''?>

      <StorageServiceProperties><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><AllowedHeaders
      /><ExposedHeaders /><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule><CorsRule><AllowedOrigins>www.xyz.com,www.ab.com,www.bc.com</AllowedOrigins><AllowedMethods>GET,PUT</AllowedMethods><AllowedHeaders>x-ms-meta-data*,x-ms-meta-target*,x-ms-meta-xyz,x-ms-meta-foo</AllowedHeaders><ExposedHeaders>x-ms-meta-data*,x-ms-meta-source*,x-ms-meta-abc,x-ms-meta-bcd</ExposedHeaders><MaxAgeInSeconds>500</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '631'
      Content-Type:
      - application/xml; charset=utf-8
      User-Agent:
      - azsdk-python-storage-blob/12.0.0b4 Python/3.7.3 (Windows-10-10.0.18362-SP0)
      x-ms-date:
      - Wed, 09 Oct 2019 21:50:43 GMT
      x-ms-version:
      - '2019-02-02'
    method: PUT
    uri: https://pyacrstorage84cb2225.blob.core.windows.net/?restype=service&comp=properties
  response:
    body:
      string: "\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server
        encountered an internal error. Please try again after some time.\nRequestId:9b76c5b7-001c-00f1-4feb-7eea73000000\nTime:2019-10-09T21:51:29.3611246Z</Message></Error>"
    headers:
      content-length:
      - '254'
      content-type:
      - application/xml
      date:
      - Wed, 09 Oct 2019 21:51:28 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      x-ms-error-code:
      - InternalError
      x-ms-version:
      - '2019-02-02'
    status:
      code: 500
      message: Server encountered an internal error. Please try again after some time.
- request:
    body: '<?xml version=''1.0'' encoding=''utf-8''?>

      <StorageServiceProperties><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><AllowedHeaders
      /><ExposedHeaders /><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule><CorsRule><AllowedOrigins>www.xyz.com,www.ab.com,www.bc.com</AllowedOrigins><AllowedMethods>GET,PUT</AllowedMethods><AllowedHeaders>x-ms-meta-data*,x-ms-meta-target*,x-ms-meta-xyz,x-ms-meta-foo</AllowedHeaders><ExposedHeaders>x-ms-meta-data*,x-ms-meta-source*,x-ms-meta-abc,x-ms-meta-bcd</ExposedHeaders><MaxAgeInSeconds>500</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '631'
      Content-Type:
      - application/xml; charset=utf-8
      User-Agent:
      - azsdk-python-storage-blob/12.0.0b4 Python/3.7.3 (Windows-10-10.0.18362-SP0)
      x-ms-date:
      - Wed, 09 Oct 2019 21:50:43 GMT
      x-ms-version:
      - '2019-02-02'
    method: PUT
    uri: https://pyacrstorage84cb2225.blob.core.windows.net/?restype=service&comp=properties
  response:
    body:
      string: "\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InternalError</Code><Message>Server
        encountered an internal error. Please try again after some time.\nRequestId:9b76fe65-001c-00f1-73eb-7eea73000000\nTime:2019-10-09T21:52:09.6518291Z</Message></Error>"
    headers:
      content-length:
      - '254'
      content-type:
      - application/xml
      date:
      - Wed, 09 Oct 2019 21:52:09 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      x-ms-error-code:
      - InternalError
      x-ms-version:
      - '2019-02-02'
    status:
      code: 500
      message: Server encountered an internal error. Please try again after some time.
version: 1
